[package]
name = "tr-worker"
version.workspace = true
edition.workspace = true
publish.workspace = true
license-file.workspace = true
[lib]
crate-type = ["rlib", "staticlib"]
[build-dependencies]
cc = "1"

[dependencies]
tr-core = { path = "../tr-core" }
image.workspace = true
png.workspace = true
tiff.workspace = true
moxcms = "=0.8.1"
anyhow.workspace = true

[dev-dependencies]
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
lcms2 = { version = "=6.2.0", features = ["static"] }
